networks:
- type: bridge
  config:
    ipv4.address: 192.0.2.1/24
    ipv4.nat: true
    ipv6.address: 2001:db8:f:1::1/64
    ipv6.nat: true
    ipv6.dhcp: false
    raw.dnsmasq: ra-param=lxdbr0,120
    bridge.hwaddr: "00:16:3e:ee:00:01"
  description: "Default network"
  name: lxdbr0
- config:
    ipv4.address: none
    ipv6.address: none
  name: hosta-to-cpe
- config:
    ipv4.address: none
    ipv6.address: none
  name: cpe-to-bb4
- config:
    ipv4.address: none
    ipv6.address: none
  name: cpe-to-bb3
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb1-to-bb2
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb1-to-bb3
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb1-to-bb4
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb2-to-bb3
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb2-to-bb4
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb3-to-bb4
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb1-to-dc
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb1-to-transit
- config:
    ipv4.address: none
    ipv6.address: none
  name: bb2-to-transit
- config:
    ipv4.address: none
    ipv6.address: none
  name: transit-to-www
- config:
    ipv4.address: none
    ipv6.address: none
  name: cn1-to-bb4

storage_pools:
- config:
    size: 15GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
