---

- name: Host provision
  hosts: default
  become: true
  tags: host
  tasks:
    - name: Include variables
      ansible.builtin.include_vars: vars/default.yaml

    - name: Install python3-apt
      command:
        cmd: apt-get -y install python3-apt
        creates: /usr/lib/python3/dist-packages/apt/package.py

    - name: Disable unattended upgrades
      apt:
        package: unattended-upgrades
        state: absent
        autoremove: yes
        purge: yes

    - name: Install necessary packages
      apt:
        package:
          - nginx
          - build-essential
          - libevent-dev
          - libncurses-dev

    - name: Setup WebSockets connection upgrade
      copy:
        src: nginx/connection_upgrade.conf
        dest: "/etc/nginx/conf.d/"
        mode: 0644
      notify: reload nginx

    - name: Disable absolute redirects
      lineinfile:
        line: "absolute_redirect off;"
        dest: "/etc/nginx/conf.d/no_absolute_redirects.conf"
        create: yes
        mode: 0644
      notify: reload nginx

    - name: Setup ttyd proxy snippet
      copy:
        src: nginx/ttydconsole.conf
        dest: "/etc/nginx/snippets/"
        mode: 0644
      notify: reload nginx

    - name: Enable ttyd proxy snippet
      lineinfile:
        path: "/etc/nginx/sites-available/default"
        line: "include /etc/nginx/snippets/ttydconsole.conf;"
        insertbefore: "^\\s*location / {.*$"
      notify: reload nginx

    - name: Setup no cache snippet
      copy:
        src: nginx/nocache.conf
        dest: "/etc/nginx/snippets/"
        mode: 0644
      notify: reload nginx

    - name: Enable no cache snippet
      lineinfile:
        path: "/etc/nginx/sites-available/default"
        line: "include /etc/nginx/snippets/nocache.conf;"
        insertbefore: "^\\s*location / {.*$"
      notify: reload nginx

    - name: Deploy static website
      copy:
        src: ../../adv6-frontend/build/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644

    - name: Deploy version file
      copy:
        src: ../../version.txt
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644

#    - name: Route everything to index.html page
#      lineinfile:
#        path: "/etc/nginx/sites-available/default"
#        line: "		try_files $uri /index.html;"
#        regexp: '^\s*try_files \$uri'
#      notify: reload nginx

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: on

    - name: Download ttyd
      get_url:
        url: "https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.{{ ansible_architecture }}"
        dest: /opt/ttyd
        mode: 0755

    - name: Deploy tmux config file
      copy:
        src: tmux.conf
        dest: "/etc/"
        mode: 0644

    - name: Deploy ttyd-container unit files
      template:
        src: "systemd/{{ item }}"
        dest: "/etc/systemd/system/"
        mode: 0644
      notify: systemctl daemon-reload
      with_items:
        - ttyd-vtysh@.service
        - ttyd-shell@.service
        - ttyd-admin.service
        - ttyd-shell.target
        - ttyd-vtysh.target

    - name: Deploy ttyd-container generators
      template:
        src: "{{ item }}"
        dest: "/etc/systemd/system-generators/"
        mode: 0755
      notify: systemctl daemon-reload
      with_items:
        - systemd/ttyd-shell.generator
        - systemd/ttyd-vtysh.generator

    - name: Enable and start ttyd targets
      service:
        name: "{{ item }}"
        state: started
        enabled: on
      loop:
        - ttyd-shell.target
        - ttyd-vtysh.target

    - name: Enable and start ttyd-admin
      service:
        name: ttyd-admin.service
        state: started
        enabled: on

    - name: Trim unused host space
      command: fstrim -av
      become: true
      changed_when: false

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

    - name: systemctl daemon-reload
      systemd:
        daemon_reload: yes


...
